// Writes dist/.htaccess for the production build (GoDaddy, Apache).
// Everything is generated from src/data/redirects.mjs so the rules and the checks never drift.
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import {
  REDIRECTS_301, GONE_PREFIXES, GONE_FILES, GONE_QUERY_KEYS, SITEMAP_REDIRECTS,
} from '../src/data/redirects.mjs';

const esc = (s) => s.replace(/[.+?^${}()|[\]\\]/g, '\\$&');
const HOST = 'sisiclinic.co.uk';

export function buildHtaccess() {
  const lines = [];
  const L = (s = '') => lines.push(s);
  L('# Generated by the site build (integrations/htaccess.mjs). Do not edit on the server:');
  L('# the next deploy overwrites this file. Change src/data/redirects.mjs instead.');
  L();
  L('Options -Indexes');
  L('DirectoryIndex index.html');
  L('ErrorDocument 404 /404.html');
  L('ErrorDocument 410 /404.html');
  L('AddDefaultCharset utf-8');
  L();
  L('<IfModule mod_rewrite.c>');
  L('RewriteEngine On');
  L();
  L('# Leave certificate validation (AutoSSL) and cPanel paths alone');
  L('RewriteRule ^\\.well-known/ - [L]');
  L('RewriteRule ^cgi-bin/ - [L]');
  L();
  L('# http -> https and www -> no www, in one hop');
  L('RewriteCond %{HTTPS} off [OR]');
  L(`RewriteCond %{HTTP_HOST} ^www\\.${esc(HOST)}$ [NC]`);
  L(`RewriteRule ^(.*)$ https://${HOST}/$1 [R=301,L]`);
  L();
  L('# Old form-entry pages from the WordPress form plugin: gone');
  L(`RewriteCond %{QUERY_STRING} (^|&)(${GONE_QUERY_KEYS.map(esc).join('|')})= [NC]`);
  L('RewriteRule ^ - [G,L]');
  L();
  L('# Old WordPress and plugin paths: gone');
  L(`RewriteRule ^(${GONE_PREFIXES.map(esc).join('|')})(/.*)?$ - [G,L]`);
  L(`RewriteRule ^(${GONE_FILES.map(esc).join('|')})$ - [G,L]`);
  L();
  L('# Old sitemaps -> new sitemap');
  L(`RewriteRule ^(${SITEMAP_REDIRECTS.map(esc).join('|')})$ /sitemap-index.xml [R=301,L]`);
  L();
  L('# Old URLs -> new URLs');
  for (const [from, to] of REDIRECTS_301) {
    L(`RewriteRule ^${esc(from)}/?$ /${to ? to + '/' : ''} [R=301,L]`);
  }
  L('</IfModule>');
  L();
  L('<IfModule mod_headers.c>');
  L('Header always set X-Content-Type-Options "nosniff"');
  L('Header always set Referrer-Policy "strict-origin-when-cross-origin"');
  L('Header always set Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=(), usb=()"');
  L('Header always set X-Frame-Options "SAMEORIGIN"');
  L('# Short HSTS first; raise to 31536000 once the new site has run cleanly for a week');
  L('Header always set Strict-Transport-Security "max-age=300"');
  L(`Header always set Content-Security-Policy "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src 'self'; connect-src 'self'; frame-src https://widget.treatwell.co.uk; form-action 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; upgrade-insecure-requests"`);
  L('<FilesMatch "\\.html$">');
  L('Header set Cache-Control "public, max-age=0, must-revalidate"');
  L('</FilesMatch>');
  L('<If "%{REQUEST_URI} =~ m#^/_astro/#">');
  L('Header set Cache-Control "public, max-age=31536000, immutable"');
  L('</If>');
  L('</IfModule>');
  L();
  L('<IfModule mod_expires.c>');
  L('ExpiresActive On');
  L('ExpiresByType image/avif "access plus 30 days"');
  L('ExpiresByType image/webp "access plus 30 days"');
  L('ExpiresByType image/jpeg "access plus 30 days"');
  L('ExpiresByType image/png "access plus 30 days"');
  L('ExpiresByType image/svg+xml "access plus 30 days"');
  L('ExpiresByType font/woff2 "access plus 1 year"');
  L('</IfModule>');
  L();
  L('<IfModule mod_deflate.c>');
  L('AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml application/javascript application/json application/xml image/svg+xml');
  L('</IfModule>');
  L();
  L('# Keep the contact script private except for the form POST');
  L('<Files "contact-config.php">');
  L('Require all denied');
  L('</Files>');
  return lines.join('\n') + '\n';
}

export function htaccess({ enabled = true } = {}) {
  return {
    name: 'sisi-htaccess',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        if (!enabled) { logger.info('preview build: no .htaccess'); return; }
        const out = new URL('.htaccess', dir);
        await writeFile(fileURLToPath(out), buildHtaccess());
        logger.info('wrote .htaccess');
      },
    },
  };
}
